// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Sxd4qDkopS8-XIVJBIlETlwCu6lTFqM',
    appId: '1:846509490664:web:ba9b2a728db634c43d245d',
    messagingSenderId: '846509490664',
    projectId: 'news-app-7d99b',
    authDomain: 'news-app-7d99b.firebaseapp.com',
    storageBucket: 'news-app-7d99b.firebasestorage.app',
    measurementId: 'G-QTXH6CXNS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCELT55-osgcmZ1h411Su9ow9Hkvze_BMg',
    appId: '1:846509490664:android:24575f8184090ccc3d245d',
    messagingSenderId: '846509490664',
    projectId: 'news-app-7d99b',
    storageBucket: 'news-app-7d99b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW87JUHQEEFOZ3kRj9lgG_xDTeQ7EqMNU',
    appId: '1:846509490664:ios:8bf6a7dc329834d03d245d',
    messagingSenderId: '846509490664',
    projectId: 'news-app-7d99b',
    storageBucket: 'news-app-7d99b.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW87JUHQEEFOZ3kRj9lgG_xDTeQ7EqMNU',
    appId: '1:846509490664:ios:8bf6a7dc329834d03d245d',
    messagingSenderId: '846509490664',
    projectId: 'news-app-7d99b',
    storageBucket: 'news-app-7d99b.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Sxd4qDkopS8-XIVJBIlETlwCu6lTFqM',
    appId: '1:846509490664:web:d023945192476f663d245d',
    messagingSenderId: '846509490664',
    projectId: 'news-app-7d99b',
    authDomain: 'news-app-7d99b.firebaseapp.com',
    storageBucket: 'news-app-7d99b.firebasestorage.app',
    measurementId: 'G-S9N6HYSN8P',
  );
}
